version: 2.1
jobs:
  build-and-lint:
    docker:
      - image: "circleci/python:3.7"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pip-deps-{{ checksum "requirements.txt" }}
            - v1-pip-deps-
      - run:
          name: Install python dependencies
          command: |
            # Install requirements
            python -m venv venv
            . venv/bin/activate
            make install
      - save_cache:
          key: v1-pip-deps-{{ checksum "requirements.txt" }}
          paths:
            - ./venv
      - run: null
        name: Install hadolint
        command: |
          wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.17.5/hadolint-Linux-x86_64
          chmod +x /bin/hadolint
      - run:
          name: Lint
          command: |
            . venv/bin/activate
            make lint
workflows:
  main:
    jobs:
      - build-and-lint
